name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-guanzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
          region-id: cn-guanzhou
      - 
        name: Build and push image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t registry.cn-guanzhou.aliyuncs.com/lunwei/clockbox:$IMAGE_TAG .
          docker push registry.cn-guanzhou.aliyuncs.com/lunwei/clockbox:$IMAGE_TAG
